// SPDX-License-Identifier: Apache-2.0
// Licensed to the Ed-Fi Alliance under one or more agreements.
// The Ed-Fi Alliance licenses this file to you under the Apache License, Version 2.0.
// See the LICENSE and NOTICES files in the project root for more information.

using Microsoft.AspNetCore.Mvc;
using Microsoft.OpenApi;
using Swashbuckle.AspNetCore.SwaggerGen;

namespace EdFi.Ods.AdminApi.Common.Infrastructure.Documentation;

/// <summary>
/// Documents the built-in <see cref="ProblemDetails"/> schema. Its properties can't carry
/// [SwaggerSchema] attributes directly since it's a framework type, so this fills in
/// descriptions here instead. Also documents the correlationId/validationErrors/errors keys
/// that V3ProblemDetailsFactory adds via ProblemDetails.Extensions, which Swashbuckle would
/// otherwise only see as an untyped additionalProperties bag.
/// </summary>
public class ProblemDetailsSchemaFilter : ISchemaFilter
{
    public void Apply(IOpenApiSchema schema, SchemaFilterContext context)
    {
        if (context.Type != typeof(ProblemDetails) || schema is not OpenApiSchema problemDetailsSchema)
            return;

        problemDetailsSchema.Properties ??= new Dictionary<string, IOpenApiSchema>();

        problemDetailsSchema.Title = "ProblemDetails";
        problemDetailsSchema.Description =
            "RFC 7807 problem details. Returned for all 4xx and 5xx responses with a content type of application/problem+json.";

        DescribeIfPresent(problemDetailsSchema, "type", "A URI reference identifying the problem type. Known values are urn:ed-fi:admin-api:bad-request, urn:ed-fi:admin-api:bad-request:data, urn:ed-fi:admin-api:bad-request:validation, urn:ed-fi:admin-api:bad-request:version-mismatch, urn:ed-fi:admin-api:not-found, and urn:ed-fi:admin-api:internal-server-error.");
        DescribeIfPresent(problemDetailsSchema, "title", "A short, human-readable summary of the problem type.");
        DescribeIfPresent(problemDetailsSchema, "status", "The HTTP status code generated for this occurrence of the problem.");
        DescribeIfPresent(problemDetailsSchema, "detail", "A human-readable explanation specific to this occurrence of the problem.");
        DescribeIfPresent(problemDetailsSchema, "instance", "A URI reference identifying the specific occurrence of the problem.");

        problemDetailsSchema.Properties["correlationId"] = new OpenApiSchema
        {
            Type = JsonSchemaType.String | JsonSchemaType.Null,
            Description = "Correlation identifier for this occurrence, present when supplied by the caller or generated by the service."
        };

        problemDetailsSchema.Properties["validationErrors"] = new OpenApiSchema
        {
            Type = JsonSchemaType.Object | JsonSchemaType.Null,
            Description = "Validation failures keyed by property name. Present on validation failures (type urn:ed-fi:admin-api:bad-request:validation).",
            AdditionalProperties = new OpenApiSchema
            {
                Type = JsonSchemaType.Array,
                Items = new OpenApiSchema { Type = JsonSchemaType.String }
            }
        };

        problemDetailsSchema.Properties["errors"] = new OpenApiSchema
        {
            Type = JsonSchemaType.Object | JsonSchemaType.Null,
            Description = "Duplicate of validationErrors, retained for compatibility with clients that read this key. Present on validation failures.",
            AdditionalProperties = new OpenApiSchema
            {
                Type = JsonSchemaType.Array,
                Items = new OpenApiSchema { Type = JsonSchemaType.String }
            }
        };
    }

    private static void DescribeIfPresent(OpenApiSchema schema, string propertyName, string description)
    {
        if (schema.Properties is not null && schema.Properties.TryGetValue(propertyName, out var property))
        {
            property.Description = description;
        }
    }
}
